# 01_inventory.R
# Deliverable 1: a verified inventory of what is on disk.
# Two datasets, each split into one file per year. Individuals row counts come
# from parquet metadata (cheap). Postings row counts stream each zip through wc
# (no unpacking). Only file-level metadata is recorded, never data rows.

source(here::here("R", "00_setup.R"))
source(here::here("R", "helpers.R"))

# --- individuals: per-file parquet metadata --------------------------------
ind_files <- individuals_files()
message(glue("[inventory] individuals files: {length(ind_files)}"))
ind_meta <- purrr::map_dfr(ind_files, function(f) {
  md <- arrow::open_dataset(f, format = "parquet")
  tibble::tibble(
    dataset = "Individuals", year = year_from_name(f),
    format = "parquet", size_b = as.numeric(fs::file_size(f)),
    n_rows = as.numeric(md$num_rows), n_cols = length(md$schema$names)
  )
})

# --- postings: per-file zip size and streamed row count --------------------
post_files <- postings_files()
message(glue("[inventory] postings files: {length(post_files)}"))
post_meta <- purrr::map_dfr(post_files, function(f) {
  tibble::tibble(
    dataset = "Postings", year = year_from_name(f),
    format = "csv.zip", size_b = as.numeric(fs::file_size(f)),
    n_rows = count_zip_rows(f),
    n_cols = ncol(read_postings_file(f, n_max = 0))  # header only, cheap
  )
})

file_meta <- dplyr::bind_rows(ind_meta, post_meta)
readr::write_csv(file_meta, fs::path(OUTPUT_DIR, "inventory_by_file.csv"))

# --- one summary row per dataset -------------------------------------------
summ <- file_meta |>
  dplyr::group_by(dataset) |>
  dplyr::summarise(
    n_files    = dplyr::n(),
    year_min   = min(year, na.rm = TRUE),
    year_max   = max(year, na.rm = TRUE),
    format     = paste(sort(unique(format)), collapse = "/"),
    total_size = format(fs::as_fs_bytes(sum(size_b, na.rm = TRUE))),
    total_rows = sum(n_rows, na.rm = TRUE),
    .groups = "drop"
  )

# --- render docs/inventory.md ----------------------------------------------
line <- function(cells) paste0("| ", paste(cells, collapse = " | "), " |")
header <- c("Dataset", "On disk?", "Format", "Files", "Years",
            "Total rows", "Total size", "Unit of obs", "Key ID(s)", "Notes / gaps")
spec <- tibble::tribble(
  ~dataset,       ~unit,        ~keys,                          ~note,
  "Individuals",  "job spell",  "user_id, position_id, rcid",   "person-level (url, linkedin_url); one file per year; pre-2012 = survivorship, treat with caution",
  "Postings",     "posting",    "job_id, rcid",                 "one file per year; 2011-2014 missing; salary fields modelled"
)
inv <- dplyr::left_join(spec, summ, by = "dataset")

rows <- purrr::pmap_chr(inv, function(dataset, unit, keys, note, n_files, year_min,
                                     year_max, format, total_size, total_rows, ...) {
  line(c(dataset, "yes", format, n_files,
         glue("{year_min}-{year_max}"),
         format(total_rows, big.mark = ","), total_size,
         unit, keys, note))
})

md <- c(
  "# Data inventory (auto-generated by R/01_inventory.R)",
  "",
  glue("Generated: {format(Sys.time(), '%Y-%m-%d %H:%M')}"),
  "Data root not shown, for governance (set via REVELIO_DATA).",
  "",
  "Row counts are verified from disk. Unit of observation and key IDs still",
  "need confirming against Revelio's documentation. Per-file detail is in",
  "output/inventory_by_file.csv.",
  "",
  line(header),
  line(rep("---", length(header))),
  rows
)
writeLines(md, fs::path(DOCS_DIR, "inventory.md"))
message(glue("[inventory] wrote docs/inventory.md and output/inventory_by_file.csv"))
